name: Triggers
on: 
    push:
        branches:
            - 'main'
    #workflow_dispatch

jobs:
    #job name
    trigger:
        runs-on: ubuntu-latest #Github hosted runners
        steps:
            #- name: Manually dispatch
             # run: echo "manually dispatch"
            - name: main branch push
              run: echo "main branch push"
