name: Triggers
on: 
    push:
        branches:
            - 'feature*'
    #workflow_dispatch

jobs:
    #job name
    trigger:
        runs-on: ubuntu-latest #Github hosted runners
        steps:
            - name: Manually dispatch
              run: echo "manually dispatch"